### ISSUE TITLE
Division by zero on migration to 2.12

### ISSUE THREAD

**Issue by Skrypt** [VirtoCommerce/vc-module-order#1]
Can be fixed by using

``
Sql("UPDATE dbo.OrderLineItem SET TaxPercentRate = Tax / (Price * Quantity - DiscountAmount) WHERE (Price * Quantity - DiscountAmount) > 0");
``

instead of 

``
Sql("UPDATE dbo.OrderLineItem SET TaxPercentRate = TaxTotal / (Price * Quantity - DiscountAmount) WHERE Price > 0 AND Quantity > 0");
``

in https://github.com/VirtoCommerce/vc-module-order/blob/master/VirtoCommerce.OrderModule.Data/Migrations/201609210923192_TotalsAndTaxesChanges.cs at line 46

**Comment by Skrypt** [comment]
I would add that the TaxPercentRate should maybe have a default value of 0 if it's a not-null database field.

**Comment by tatarincev** [comment]
Thanks for PR. But MSSQL already use 0 value for not-null decimal columns,  isn't it?

**Comment by Skrypt** [comment]
Not sure about that one. I think you don't get any errors because you are filling the table with data. But normally when adding a not-null field with the SQL Management Studio it will warn you that you need to have a default value set else it will fail on a table that has already records. The workaround to not have that default value set is to drop it afterward.

**Comment by Skrypt** [comment]
You can close this, I think that's how Entity Framework handles it's automated code first migrations. So nothing to fix here. You can close unless you see something else in here.
