### ISSUE TITLE
Register metafields on filter-detail blade

### ISSUE THREAD

**Issue by AkulovOleg** [VirtoCommerce/vc-module-order#103]
We can't add metafields to this blade: 
https://github.com/VirtoCommerce/vc-module-order/blob/dev/VirtoCommerce.OrderModule.Web/Scripts/blades/filter-detail.tpl.html#L14

https://github.com/VirtoCommerce/vc-module-order/blob/dev/VirtoCommerce.OrderModule.Web/Scripts/blades/filter-detail.js

**Comment by yecli** [comment]
Filter-details blade extension example given `platformWebApp.metaFormsService` included as `metaFormsService`:
```
        metaFormsService.registerMetaFields("orderFilterDetail", [{
                name: 'Additional',
                title: 'Addtional title',
                valueType: 'ShortText',
            },
        ]);
```

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-order/releases/tag/v2.17.24
