### ISSUE TITLE
`customer` and `assign to` fields don't work on `orderFilterDetail` blade

### ISSUE THREAD

**Issue by AkulovOleg** [VirtoCommerce/vc-module-order#105]
On "orderFilterDetail" blade don't work fields "customer" and "assing to"

**Comment by yecli** [comment]
@akak1977 Could you please add backward compatibility support to vc-module-core as proposed [here](https://github.com/VirtoCommerce/vc-module-core/pull/123#issuecomment-502336719)? This will allow us to not use CustomerId in vc-module-order.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-order/releases/tag/v2.17.24
