### ISSUE TITLE
Shipment line item in order

### ISSUE THREAD

**Issue by IvanTsel96** [VirtoCommerce/vc-module-order#107]
Don't show shipment item information in admin. 
Presumably not working ToModel method in ShipmentItemEntity class. LineItem don't fill.

![image](https://user-images.githubusercontent.com/48719896/59416970-0dc0da00-8dcf-11e9-82f7-5ca3cdd03751.png)

**Comment by yecli** [comment]
Shipment items form is not completed functionally and can't be used.
If you have specific requirements for functional part - please describe them, we'll include them into backlog.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-98
