### ISSUE TITLE
Create CustomerOrder by constructed ShoppingCart

### ISSUE THREAD

**Issue by ksavosteev** [VirtoCommerce/vc-module-order#108]
Currently CreateOrderFromCart API takes cartId as an argument.
Need to add a new API method that takes ShoppingCart object as an argument then creates (saves 
and returns) CustomerOrder from it.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-52
