### ISSUE TITLE
Cancel order operation does not throw a validation error when "reason" field has no value

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-order#12]
Version info: 
- Browser version: Chrome 60
- Platform version: 2.13.14
- Module version: 2.16.4

### Expected behavior
Order cancellation confirmation dialog must throw a validation error when textarea is not filled or accept empty textarea.

### Actual behavior
Module just do nothing & don't throw any errors when you try to cancel order without reason.

### Steps to reproduce
1. Go to any order
2. Cancel order
3. Leave "Please enter cancel reason here..." textarea empty
4. Click to Confirm
Nothing happens. Order is not cancels and do not throw any error.

**Comment by andshk** [comment]
What behavior would be more superior: let a user leave textarea empty or force him to fill it?

**Comment by tatarincev** [comment]
For the first need to check why the system didn't show any error when a user leaves reason tex-area empty.
And then if reason field is required in database schema we should also make this field as required in the UI.

**Comment by andshk** [comment]
The field is optional. If tex-area is empty and user hits Confirm button nothing sends to the server side.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-order/releases/edit/v2.17.4
