### ISSUE TITLE
Don't throw an exception if the operation template is not found

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-order#163]
Version info: 
- Platform version: 2.13.52
- Module version: 2.17.31

### Expected behavior
Display document tree correctly.

### Actual behaviour
The document tree is broken if UI template is not defined for one of the operations.

### Steps to reproduce
1. Create custom order document
2. Don't add UI

https://github.com/VirtoCommerce/vc-module-order/blob/support/2.x-dev/VirtoCommerce.OrderModule.Web/Scripts/widgets/operation-tree-widget.js#L16

**Comment by lnetrebskii** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-2892 has been created
