### ISSUE TITLE
Filtering with Lucene

### ISSUE THREAD

**Issue by danielstarzewski** [VirtoCommerce/vc-module-order#19]
Hello,
Is there a way to change the filtering functionality in Orders blade so that it uses Lucene engine? I would like to have the same filtering mechanism as for product catalogue. Can I do that any other way than overriding existing controller and template for orders list?
Thank you.
Daniel

**Comment by asvishnyakov** [comment]
@artem-dudarev May you explain?

**Comment by danielstarzewski** [comment]
Doesn't matter anymore. I have already replaced files I had to. Built is support for this would be an asset though.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
