### ISSUE TITLE
Role-based misbehaviour on order summary

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-order#220]
Version info: 
- Browser version: Any
- Platform version: 2.13.65
- Module version: 2.17.26

### Expected behavior
As an Administrator, I want to see order price 

### Actual behavior
As an Administrator, I see 0 price until I assign a role with order:read_price permission

### Steps to reproduce
1. Sigin as Administator and Role without order:read_price permission
2. Open Any Order
3. See zero price

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-6977 has been created

**Comment by OlegoO** [comment]
Fixed in
https://github.com/VirtoCommerce/vc-module-order/releases/tag/v2.17.27
