### ISSUE TITLE
Concurrency problem (First: Publish Notification Second: ComitAsync)

### ISSUE THREAD

**Issue by corneliusmunz** [VirtoCommerce/vc-module-order#224]
Concurrency Problem if a order is changed and the Reciver of the notification will also change some properties. 

Version info: 
- Browser version:  Chrome 89.0.4389.90
- Platform version: 3.39.0
- Module version: 3.26.0

### Expected behavior
Send out notification of changed order after the changes are comitted to the repository

### Actual behavior
Notification is send out before the changes are comitted to the repository

We have faced and concurrency issue in an custom module which receives the order changed notification and updates some properties after processing the order with the OrderService.SaveChangesAsync method. 

With the current implementation the folow is as follows:

1. Order ist changed
2. SaveChangesAsync is called
3. Notifcation is send out and awaited
4. Notification receiver call SaveChangesAsync again
5. ComitAsync is called for the first/second SaveChangesAsync call (concurrency/ race condition)

I would suggest the following order of calls in the CustomerOrderService.cs class (Line 160,161):
``` c#
await repository.UnitOfWork.CommitAsync();
await _eventPublisher.Publish(new OrderChangeEvent(changedEntries));
```

With this change i got rid of the concurrency and strange behaviour of saving properties of the order entity

### Steps to reproduce
1. 
2.
3.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7322 has been created

**Comment by tatarincev** [comment]
Hi @corneliusmunz I suppose you are using the wrong event.

In virto we have the two types of events for changed entities that are emitted  Before (OrderChangeEvent) and After (OrderChang**ed**Event) order saving. For your case, if you want to avoid race conditions when saving, you have to handle  OrderChang**ed**Event instead of OrderChangeEvent. Does that make sense?

**Comment by corneliusmunz** [comment]
Hi @tatarincev ! Thanks for the fast response! We have registered for the following event: 
```c#
 eventHandlerRegistrar.RegisterHandler<OrderChangedEvent>((message, token) => appBuilder.ApplicationServices.GetService<SplitOrderModuleOrderChangedEventHandler>().Handle(message));
```

So i think it is the correct one. But you are right, the published Event in the Order module in that case is the correct one (OrderChang**e**Event) and not OrderChang**ed**

So we try to have a deeper look why our Addresses are overwritten. In our module we use the object which is send via the Eventhandler and use that object to store changes via the Service `SaveChangesAsync` in the OrderModule. Would it be better to  fetch the object again befor saving it in our custom module?

**Comment by tatarincev** [comment]
Yes, this is definitely a good solution for a handler to read an object before saving. Unfortunately, the platform hasn't included an optimistic update conflict resolution yet, but we have some plans about this.

**Comment by tatarincev** [comment]
But keep in mind the infinitive recursion that might be.
