### ISSUE TITLE
'Delete' order should put the list in isLoading state until operation is done.

### ISSUE THREAD

**Issue by danielstarzewski** [VirtoCommerce/vc-module-order#23]
Hi,
1. Visit demo site.
2. Go to Orders list.
3. Select one order.
4. Click 'Delete'.
Expected behavior: Loader appears on the list to indicate operation is in progress.
Actual behavior: In my case request was processing for 13s (this is a lot). During that time UI was editable - showing no loader. After the request ended Loader showed up for short time.

**Comment by andshk** [comment]
I've tried to reproduce this issue several times using Chrome, Firefox, and IE. Everything behaves as it expected to be. This problem is unreproducible in my environment.

**Comment by danielstarzewski** [comment]
Could you please try it in demo environment?

**Comment by andshk** [comment]
Sure, but where i can get that demo environment? Could you please to send me a link on it?

**Comment by danielstarzewski** [comment]
http://admin-demo.virtocommerce.com/?utm_source=autopilot&utm_campaign=trial&utm_medium=email#/workspace/orders

**Comment by andshk** [comment]
After signing in, I have this window on my screen, and nothing changes within 25 minutes or so. How long can it take?
![screenshot-admin-demo virtocommerce com-2018-01-15-12-51-19-464](https://user-images.githubusercontent.com/30589866/34936728-8ae4307a-f9f3-11e7-8321-344feff34662.png)

**Comment by danielstarzewski** [comment]
I believe this is another bug of yours. As a workaround you can do this:
![image](https://user-images.githubusercontent.com/30530759/34937983-eea778b8-f9e6-11e7-97e7-d6ecea33d91c.png)
Right click on the back button and select previous page.

**Comment by danielstarzewski** [comment]
![image](https://user-images.githubusercontent.com/30530759/34938055-2fd0d2b2-f9e7-11e7-903b-d7b6b4231cba.png)

**Comment by andshk** [comment]
Again everything behaves as it should be. I see no issues described above.

**Comment by andshk** [comment]
Could you explain to me how I can a attach to that remote environment?

**Comment by danielstarzewski** [comment]
Between second 1 and 2 there is a state when no loader appears but the request is being processed. Then loader appears. I think the delay is longer when more orders is on the list.
[2018-01-15_11-49-16.zip](https://github.com/VirtoCommerce/vc-module-order/files/1631353/2018-01-15_11-49-16.zip)
@tatarincev please help @andshk with his question.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-order/releases/edit/v2.17.4
