### ISSUE TITLE
view packages in shippements

### ISSUE THREAD

**Issue by JoseCaetanoNeto** [VirtoCommerce/vc-module-order#260]
### Expected behavior

Show packages details in Shipments items UI

### Actual behavior

Packages is hide in Shipments items UI

### Steps to reproduce
1. record shipment Package in database with items
2. Open backend
3. Go to the Orde detail, select in tree view shipment item
4. Select shipment items
5. Only items is show, package info is hiden

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7712 has been created

**Comment by dvvkgd** [comment]
@JoseCaetanoNeto The 'package []' attribute contains many fields. May I ask you: what fields (package info) would you like to see in the shipping document in the admin UI? What packing fields are you working with?

**Comment by JoseCaetanoNeto** [comment]
In addition to the information that the items already bring today, I think it is necessary to have at least "Barcode" and "PackageType" fields
