### ISSUE TITLE
"PaymentMethod.VoidProcessPayment" or "PaymentMethod.RefundProcessPayment" no fired on cancel only Payment

### ISSUE THREAD

**Issue by JoseCaetanoNeto** [VirtoCommerce/vc-module-order#261]
Version info: 
- Browser version: 
- Platform version: VirtoCommerce.Platform.3.79.0
- Module version: VirtoCommerce.Orders_3.37.0

### Expected behavior
Cancel Payment Handle fire on only a Payment is Cancel

### Actual behavior

Cancel Payment Handle not fire "PaymentMethod.VoidProcessPayment" or "PaymentMethod.RefundProcessPayment" if only canceled Payment. Cause bug, the Payment card  not canceled in payment Gateway

Then bug is caused, because Background Job run after data is save, and exists a check in code, if payment is was cancel prior

method : **TryToCancelOrderPaymentsAsync(PaymentToCancelJobArgument[] jobArguments)**

```
 if (paymentToCancel != null && !paymentToCancel.IsCancelled)
 {
      CancelPayment(paymentToCancel, order);

       if (!changedOrders.Contains(order))
       {
            changedOrders.Add(order);
       }
 }

```
### Steps to reproduce
1. Make Order
2. Cancel only Payment
3. "PaymentMethod.VoidProcessPayment" or "PaymentMethod.RefundProcessPayment" are no fired

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7713 has been created

**Comment by OlegoO** [comment]
Thank you for the issue, I forwarded it to Dev Team

**Comment by ksavosteev** [comment]
@JoseCaetanoNeto 
Introduced a fix in https://github.com/VirtoCommerce/vc-module-order/releases/tag/3.40.0
Added a new property to Payment entity - `CancelledState`, to cancel a payment set this property to `Requested` and save the order.
