### ISSUE TITLE
Update order with more than one dynamic property leads to wrong properties (merged values)

### ISSUE THREAD

**Issue by corneliusmunz** [VirtoCommerce/vc-module-order#271]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version:  doesn't matter (backend issue)
- Platform version:  v3.80.0
- Module version: 3.43.0 (current release)

### Expected behavior
If i add two dynamic properties to an existent order with no dynamic properties and update the order via the API i would expect to see two dynamic properties with their values.

The same would be expected if i add more than two properties and update the order via the API

### Actual behavior
If i add two dynamic properties to an exsitent order and update the order via API i will get ONE dynamic property with all the values of the two dynamic properties MERGED in that ONE dynamic property. 

--> Seems to be a bug in the following line of code where a GroupBy statement is done on the PropertyId which is for the new properties both "null". If i change the line to GroupBy Id instead of PropertyId, it works

https://github.com/VirtoCommerce/vc-module-order/blob/78c71461e84294a904cdf56fead2e0c280b69900/src/VirtoCommerce.OrdersModule.Data/Model/CustomerOrderEntity.cs#L149

### Steps to reproduce
1. create order from cart without any dynamic properties
2. Update order with two different dynamic properties
3. Fetch order and look into the DynamicProperties

**Comment by dvvkgd** [comment]
@corneliusmunz Could you please show an example query how you create new dynamic properties for orders (update orders)? (**"dynamicProperties":[]** section)

**Comment by dvvkgd** [comment]
@corneliusmunz I can suggest the workaround:
to work with dynamic properties, You first needs to create them and then use their ID for 'PropertyId' field. I hope, it helps You.
![image](https://user-images.githubusercontent.com/50042902/137925777-4e2d2855-9609-41a8-bb29-4d6b6fc56bb8.png)
![image](https://user-images.githubusercontent.com/50042902/137925856-94ddbd95-8341-4f71-82e6-857c2a593a14.png)
![image](https://user-images.githubusercontent.com/50042902/137925952-4974e08d-d663-458a-ad29-1415e22a2abb.png)

We will also create a task to handle this scenario and support dynamic properties without PropertyID.
