### ISSUE TITLE
BeforeSaveChanges not called in CustomerOrderService.SaveChanges

### ISSUE THREAD

**Issue by azapotoczny-forte** [VirtoCommerce/vc-module-order#367]
Version info: 
- Browser version: not relevant
- Platform version: 3.317.0
- Module version: 3.245.0

`CrudService` calls `BeforeSaveChanges` method when saving changes.  `CustomerOrderService` inherits from `CurdService` and changes that behavior. This violates the Liskov Substitution Principle.

**Comment by OlegoO** [comment]
@azapotoczny-forte Thank you for feedback, we will resolve it max in next two weeks (current sprint).
https://virtocommerce.atlassian.net/browse/PT-13270

**Comment by OlegoO** [comment]
https://github.com/VirtoCommerce/vc-module-order/pull/374/files
