### ISSUE TITLE
Is paid compare error

### ISSUE THREAD

**Issue by ruyi-kooboo** [VirtoCommerce/vc-module-order#37]
Location:VirtoCommerce.OrderModule.Data.Observers.OrderNotificationObserver.IsOrderPaid(Line 131)
Tips:var 'paidSum' have two decimal places,but value.ModifiedOrder.Total maybe have three decimal places

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
