### ISSUE TITLE
Missing shipping and payment methods in OrderChangedEvent data

### ISSUE THREAD

**Issue by j-mok** [VirtoCommerce/vc-module-order#388]
Version info: 
- Platform version: 3.426.0
- Module version: 3.415.0

### Expected behavior
* `OrderChangedEvent.ChangedEntries[].NewEntry.InPayments[].PaymentMethod` is loaded before `OrderChangedEvent` is emitted 
* `OrderChangedEvent.ChangedEntries[].NewEntry.Shipments[].ShippingMethod` is loaded  before `OrderChangedEvent` is emitted 

### Actual behavior
The mentioned properties are reset to `null` between `OrderChangeEvent` and `OrderChangedEvent`. It happens [here](https://github.com/VirtoCommerce/vc-module-order/blob/58ab379be8ed3e91c4aee88a57e3350c0ba001da/src/VirtoCommerce.OrdersModule.Data/Services/CustomerOrderService.cs#L142-L151). I believe the last Orders Module version for VC2 had a different behavior.

### Steps to reproduce
1. Add a handler for `OrderChangedEvent`
2. Change a status or anything else on an order and save
3. Observe missing data in the handler

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8478 has been created

**Comment by OlegoO** [comment]
Fixed with https://github.com/VirtoCommerce/vc-module-order/releases/tag/3.425.0
