### ISSUE TITLE
Incorrect DateTimeKind in OrderChangedEvent handler

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-module-order#41]
When a new order is created, the `OrderChangedEvent` handler receives a `NewEntry` object that has incorrect `CreatedDate` value - it is a UTC date/time, but its `Kind` property is `DateTimeKind.Uncpecified` instead of `DateTimeKind.Utc`.

The same issue applies to `OldEntry` when updating an existing order - both `CreatedDate` and `ModifiedDate` have `DateTimeKind.Uncpecified`.

Converting such dates to some specific timezone gives incorrect result.

**Comment by tatarincev** [comment]
Seems it is EF limitation (All DateTime properties was materialized  with `DateTimeKind = Unspecified`)
https://volosoft.com/datetime-specifykind-in-entity-framework-core-while-querying/

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
