### ISSUE TITLE
Order payment transactions tab is not clickable

### ISSUE THREAD

**Issue by zhangpengchen** [VirtoCommerce/vc-module-order#42]
VirtoCommerce Platform Version: 2.13.26
VirtoCommerce Order Module Version: 2.17.11

When you click the transactions tab for an order, nothing happened, no console errors, or ajax calls and so on.
![transactions](https://user-images.githubusercontent.com/4378651/40241964-9058a124-5abc-11e8-9555-215e6d2f458b.png)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-order/releases/tag/v2.17.12
