### ISSUE TITLE
DynamicProperties is null in OldEntry

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-module-order#43]
### Expected behavior
old DynamicProperties are filed and available in GenericChangedEntry<CustomerOrder> OldEntry
### Actual behavior
DynamicProperties are always null in GenericChangedEntry<CustomerOrder> OldEntry
### Steps to reproduce
1. create test DynamicProperty for CustomerOrder (in admin UI) if it's missing;
2. fill the dynamic property for any order (in admin UI);
3. subscribe to OrderChangedEvent and check the data received OR debug what data is sent to OrderChangedEvent in code.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-order/releases/tag/v2.17.16
