### ISSUE TITLE
Failed rendering of order notifications caused to fail order creation

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-order#48]
Version info: 
- Browser version: Chrome 66
- Platform version: 2.13.32
- Module version: 2.17.15
- Storefront version: latest dev

If order paid (and, possible, order created) notification has incorrect syntax, then order creation on storefront will fail because order event handler will throw platform exception.

How to reproduce:
1. Create broken order paid template (for example, "{% fake %}"
2. Try to create order on storefront
3. Select test method for shipment & payment

**Comment by eMazeika** [comment]
@asvishnyakov and what's the expected behavior?

**Comment by asvishnyakov** [comment]
@eMazeika Not for us. So at least we need settings for that, but I believe rendering errors should not cause order creation fail at all.
