### ISSUE TITLE
Allow to search orders by organization id

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-order#50]
Extend domain model for search criteria, make implementation & extend storefront search criteria

**Comment by eMazeika** [comment]
https://github.com/VirtoCommerce/vc-module-core/pull/75

**Comment by tatarincev** [comment]
Need to extend the current order search  logic https://github.com/VirtoCommerce/vc-module-order/blob/master/VirtoCommerce.OrderModule.Data/Services/CustomerOrderServiceImpl.cs#L189
to allow search orders by new order search criteria property `OrderSearchCritera.OrganizationId`
https://github.com/VirtoCommerce/vc-module-core/blob/dev/VirtoCommerce.Domain/Order/Model/Search/CustomerOrderSearchCriteria.cs#L96

Also, need to write the new unit test which will covers this case

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-order/releases/tag/v2.17.16
