### ISSUE TITLE
Order operations disappearing from UI

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-module-order#60]
Order operations disappearing from UI after "Payment fees" value changed:
http://recordit.co/imXvGFrFCb

Order operations should stay in UI.

**Comment by avas** [comment]
During the work on this issue, I noticed a strange behavior: even after updating the payment amounts, the payment node in the operations tree still displays the old value.
![image](https://user-images.githubusercontent.com/1835759/46013051-37c55580-c0f5-11e8-93e0-84f490f55587.png)

Is it supposed to work this way? Should I fix it?

**Comment by tatarincev** [comment]
https://github.com/VirtoCommerce/vc-module-order/releases/tag/v2.17.20

**Comment by tatarincev** [comment]
@avas How I can reproduce this error?

**Comment by avas** [comment]
@tatarincev If you're talking about [this error](https://github.com/VirtoCommerce/vc-module-order/issues/60#issuecomment-424314625), then it is really easy:
1. Open any order that has incoming payment.
2. Select that incoming payment.
3. In the incoming payment details blade, change value of `Payment fees` and `Amount` fields.
4. Click `OK`.

Expected result (?): total value on the `PaymentIn` tree item should change and (probably) should match `Total` value from the incoming payment details blade. At least Shipment details blade works that way.
Actual result: total value remains unchanged.

**Comment by tatarincev** [comment]
@avas The payment widget displays a amount that isn't supported by manual editing. This is the right behavior.
