### ISSUE TITLE
Recalculate API Doesn't Recalculate Totals

### ISSUE THREAD

**Issue by benb1n** [VirtoCommerce/vc-module-order#62]
https://github.com/VirtoCommerce/vc-module-order/blob/e7b7a3e712186fa938ae97e5af0446cdc5807308/VirtoCommerce.OrderModule.Web/Controllers/Api/OrderModuleController.cs#L166

This doesn't appear to do anything.  Should it make a call to `ICustomerOrderTotalsCalculator.CalculateTotals()`?  

I passed an order with an updated line item quantity to this method and it didn't update the total.

@tatarincev

**Comment by tatarincev** [comment]
I've added missed logic

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-order/releases/tag/v2.17.19
