### ISSUE TITLE
fix displayed value in Revenue widget on Dashboard

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-module-order#71]
![image](https://user-images.githubusercontent.com/5801549/49865094-aa002900-fe0c-11e8-8f2b-c4449098704e.png)

**Expected behavior**
the value should be bound to 'revenue' property

**Comment by yecli** [comment]
Released in [v2.17.22](https://github.com/VirtoCommerce/vc-module-order/releases/tag/v2.17.22).
