### ISSUE TITLE
Add permission which could manage prices visibility

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-module-order#80]
We need to add new scope for ''order:read" that could limit returned order data by specifying `CustomerOrderResponseGroup`'s. As a specific case, we want to be able to return orders with no amounts info (prices/discounts/taxes).
![image](https://user-images.githubusercontent.com/15610352/53952699-4f1c5c00-40f3-11e9-8182-b6921f0d3c07.png)
Prices in selected places should not be shown, API should not return info on them.

**Main idea:**
If user have scope OrderLimitResponseScope in 'order:read' permission - we return all orders data except response groups specified in the scope.
In case user do not have that scope under 'order:read' permission - all data are returned (means no changes for already existing users).

**Technical details:**
**vc-module-core**
- Need to extend [CustomerOrderResponseGroup](https://github.com/VirtoCommerce/vc-module-core/blob/025ae6e5722f49033899122994c9a65aad22d5fe/VirtoCommerce.Domain/Order/Model/CustomerOrderResponseGroup.cs#L10) with element `WithAmounts`, and include it in `Full` element;

**vc-module-order**

- When we handling orders API request in [OrderModuleController](https://github.com/VirtoCommerce/vc-module-order/blob/dev/VirtoCommerce.OrderModule.Web/Controllers/Api/OrderModuleController.cs), we need to check for OrderLimitResponseScope scope existence and exclude selected scopes from returned response group;

- Need to add an ability to nullify amount values for orders that API returns. It could be achieved by one of the following ways:
1. Create own entities for different order objects amounts (e.g. by using [EF ComplexType](https://stackoverflow.com/questions/9931341/entity-framework-reuse-complex-type)) and not load/clear them based on ResponseGroup. This would require core models change, also need to support backward compatibility in that case;
2. In service [CustomerOrderServiceImpl](https://github.com/VirtoCommerce/vc-module-order/blob/2e9bc2a024d6a65c255f8aaa5086fcb3113e73f8/VirtoCommerce.OrderModule.Data/Services/CustomerOrderServiceImpl.cs#L121) we could clear amount values for order objects;

- When updating entities, we need to skip updating properties for the Response group we do not have rights to. For amounts, it could be done by skipping fields update if we have no data for in Patch methods (e.g. [CustomerOrderEntity.Patch](https://github.com/VirtoCommerce/vc-module-order/blob/dev/VirtoCommerce.OrderModule.Data/Model/CustomerOrderEntity.cs#L159)). Need to carefully check if we have no data for the object - all non calculated non nullable amount properties (probably decimal or int) should be default value of that type. E.g. for LineItem these amounts are `TaxPercentRate`, `Price`, `DiscountAmount` and `Quantity`, looking at [TotalsCalculator](https://github.com/VirtoCommerce/vc-module-order/blob/2e9bc2a024d6a65c255f8aaa5086fcb3113e73f8/VirtoCommerce.OrderModule.Data/Services/DefaultCustomerOrderTotalsCalculator.cs#L165);

**UI**
- Add scope OrderLimitResponseScope that allow to choose restricted ResponseGroups (it should be multiselect dictionary as [OrderStoreScope](https://github.com/VirtoCommerce/vc-module-order/blob/dev/VirtoCommerce.OrderModule.Web/Security/OrderStoreScope.cs) based on some of CustomerOrderResponseGroup enum values - now only new WithAmounts is must-have value):
![image](https://user-images.githubusercontent.com/15610352/54205634-8c6c5980-44f8-11e9-8469-aff654ccce81.png)

- Hide amounts on the orders blades and widgets based on the scope value;

**Comment by IgorisB** [comment]
**[Security issues]** Why encrypt/decrypt prices? "Visibility" means we don't need to return any amounts or values in the backend API response at all. 
**[Compatibility issues]** this feature will impact existant solutions because this permission is not by default and prices/amounts will be hidden after update. So custom projects will require to make changes in users permissions.
**[Suggestion]** Add a scope to order:read permission like "Show Amounts" = true/false (with true by default)
**[Note]** Make sure not only prices but all order amounts are hidden. So term "Show amounts" is more correct in this case.


@tatarincev please review

**Comment by yecli** [comment]
Encrypt/decrypt were proposed for saving data from the client - that way we could get prices from encrypted data from the client side. In case we want to avoid these security risks - we could use clearing/loading amounts on API controllers side instead.

Good idea about scope in order:read, maybe it could be something like "HideAmounts" for compatibility (so its absence would leave current behavior).

**Comment by IgorisB** [comment]
the feature is about limiting reading, not saving, updating or encrypting data. 
"HideAmounts" sounds good.

**Comment by tatarincev** [comment]
@IgorisB  Encrypt/decrypt is required due of peculiarities of working our update logic (order aggregate is  saved with all it properties, no partial update allowed) therefore there are may be situations when user who not have permissions to see a prices, have permissions to update order e.g status or do some other actions that can lead to save order object and  empty properties  with amounts (removed before on read operation)  will replace original values in DB.

**Comment by OlegoO** [comment]
@tatarincev @yecli 
I agree with @IgorisB we should not return any data if a user doesn't have the permission. 

To encrypt/decrypt the value, you would need to change the data model and it will crash the current clients. 

I offer 
1. use Data Masking and return for example Zero value
2. If I could not read the price, I could not update the price
3. Update admin UI to hide the data if I don't have the permission

**Comment by asvishnyakov** [comment]
Do you any use cases for that situation? I can't imagine situation when customer who can change order itself can't see prices in order

**Comment by OlegoO** [comment]
@asvishnyakov  I had the discussion with @tatarincev and @IgorisB. @tatarincev will reorganize this ticket to split Price and Total amount int own entities  (with back capabilities), add a new response group WithPrice and extend grant read permission with Response groups scope. So, we can limit read access to specific response groups.

**Comment by yecli** [comment]
Updated description according to the discussion results.

**Comment by alexx1524** [comment]
- [ ] Add item WithPrices in the enumeration CustomerOrderResponseGroup. Add to Full. Make PullRequest.

- [ ] Create an OrderLimitResponseScope inherited from PermissionScope 
(VirtoCommerce.OrderModule.Web, Security directory), and register it in module.cs (PostInitialize())

- [ ] Add a list of valid items from the enumeration CustomerOrderResponseGroup to OrderLimitResponseScope

- [ ] In the method GetCustomerOrdersByIds of repository OrderRepositoryImpl.cs reset not calculated base prices if the WithPrices flag in ResponseGroup is not set

- [ ] Add a processing element CustomerOrderResponseGroup.WithPrices to the method 
 GetCustomerOrdersByIds of OrderRepositoryImpl.cs repository

- [ ] Change the path method of entities (prices changing is available only if at least one value is not 0)

- [ ] Development of unit tests

- [ ] All the methods for selecting orders in OrderModuleController.cs should work according to the 
OrderLimitResponseScope

- [ ] Add a new OrderLimitResponseScope element to the list for the order:read role

- [ ] Automatically add all items to OrderLimitResponseScope when role created or order:read rights added

- [ ] Hide price on the LineItemsWidget of the order details blade

- [ ] Hide the CustomerOrderTotalsWidget on the order details blade

- [ ] Hide prices on the OrderOperationDetail widget

- [ ] Hide prices on the ShipmentDetail blade

- [ ] Hide prices on the PaymentDetail blade

- [ ] Hide prices on the OrderLineItems blade

**Comment by alexx1524** [comment]
![_1](https://user-images.githubusercontent.com/4988205/55005512-2cdc7680-4fed-11e9-9e9a-350b12dfc4fd.gif)

**Comment by alexx1524** [comment]
![_2](https://user-images.githubusercontent.com/4988205/55005541-3bc32900-4fed-11e9-869c-9a28e9c4eeca.gif)

**Comment by yecli** [comment]
Released in [v2.17.23](https://github.com/VirtoCommerce/vc-module-order/releases/tag/v2.17.23).
