### ISSUE TITLE
CreatedDate is copied from the cart

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-module-order#82]
In our Dashboard, in Power BI we rely on the CreatedDate Column. It gives a Date for every single OrderLine. 

We found that, First OrderLine is 29 January (week 4). The second OrderLine is 1 February (Week 5). 

Then we found that CreatedDate is copied from the cart. So CreatedDate is placed to cart date
https://github.com/VirtoCommerce/vc-module-order/blob/dev/VirtoCommerce.OrderModule.Data/Services/CustomerOrderBuilderImpl.cs#L131

Remove it to have correct Order CreatedDate on line item level.

**Comment by yecli** [comment]
Released in [v2.17.22](https://github.com/VirtoCommerce/vc-module-order/releases/tag/v2.17.22).
