### ISSUE TITLE
Add some data optimization for loading orders to display in list

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-order#86]
**Problem description:**
The current UI for display order list used search request with Full response group (it is used by default), so this leads to excess data loading that aren't  used in UI.
![image](https://user-images.githubusercontent.com/7566324/54825471-511b1900-4cb6-11e9-8832-f4fcc6ff85b8.png)
**Solution:**
Use "Default" response group for search orders and populate list

**Comment by yecli** [comment]
Released in [v2.17.23](https://github.com/VirtoCommerce/vc-module-order/releases/tag/v2.17.23).
