### ISSUE TITLE
Totals calculation is skipped due to inconsistent CustomerOrderResponseGroup

### ISSUE THREAD

**Issue by mvsmal** [VirtoCommerce/vc-module-order#91]
Method `CustomerOrderServiceImpl.GetByIds()` skips Totals calculation if the `CustomerOrderResponseGroup`, located in VirtoCommerce.Domain package, is of a newer version.

In VirtoCommerce.Domain v.2.25.19 the `CustomerOrderResponseGroup.WithPrices` case was added. Therefore the `CustomerOrderReponseGroup.Full` integer representation has been changed to `63`. `OrderModule` depends on v.2.25.13, which has `CustomerOrderResponseGroup.Full == 31`. Thus, the comparison of `Full == Full` fails.

It is related to the .NET optimization, which, apparently, inlines the `CustomerOrderResponseGroup.Full` and then compares the real value with a constant.

https://github.com/VirtoCommerce/vc-module-order/blob/dev/VirtoCommerce.OrderModule.Data/Services/CustomerOrderServiceImpl.cs#L121-L124 :
```csharp
if (orderResponseGroup == CustomerOrderResponseGroup.Full)
{
    TotalsCalculator.CalculateTotals(customerOrder);
}
```

This may happen to any enum, located in a shared package. One possible solution is to create `CusomerOrderResponseGroup` at runtime, for example:
```csharp
if (orderResponseGroup == EnumUtility.SafeParse("Full", CustomerOrderResponseGroup.Full)
```
However this might also be optimized by the compiler. Needs to be checked.

**Comment by yecli** [comment]
Seems it does not help.
The condition evaluates to false now on my side with 2.25.13 and 2.25.19 Domain dll references in different modules.
```
var orderResponseGroup = EnumUtility.SafeParse(responseGroup, CustomerOrderResponseGroup.Full);
…            
if (orderResponseGroup == EnumUtility.SafeParse(nameof(CustomerOrderResponseGroup.Full), CustomerOrderResponseGroup.Full))
{
    TotalsCalculator.CalculateTotals(customerOrder);
}
```
That's strange. So for now, will update dependency for Core module to solve the problem.

**Comment by yecli** [comment]
We should avoid using enums from other dll-s at all, as it is a compile time constants: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/enum#robust-programming.
So we need to exclude public enums from shared Core module.
