### ISSUE TITLE
Query optimization based on collection emptiness

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-module-order#96]
Need to optimize [`OrderRepositoryImpl.GetCustomerOrdersByIds`](https://github.com/VirtoCommerce/vc-module-order/blob/dev/VirtoCommerce.OrderModule.Data/Repositories/OrderRepositoryImpl.cs#L246) method the same way as it was done in https://github.com/virtocommerce/vc-module-cart/issues/34.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-order/releases/tag/v2.17.24
